In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
A = np.array([[1,1,1],
              [1,2,-1],
              [2,1,2]])
B = np.array([6,2,10])
# menggabungkan matriks A dan B
X = np.concatenate((A,B.reshape(3,1)), axis=1)
print(X)

[[ 1  1  1  6]
 [ 1  2 -1  2]
 [ 2  1  2 10]]


In [16]:
#Algoritma eliminasi Gauss 
def eliminasi_gauss(X):
    n = len(X)
    for k in range(n-1):
        for i in range(k+1,n):
            if X[i,k] != 0:
                lamda = X[i,k]/X[k,k]
                X[i,k+1:n] = X[i,k+1:n] - lamda*X[k,k+1:n]
                X[i,k] = 0
    return X
hasil = eliminasi_gauss(X)
print(hasil)

[[ 1  1  1  6]
 [ 0  2 -1  2]
 [ 0  0 -2 10]]
